---
- name: pre
  shell: "echo 123"

- name: Create ElasticSerach Data Dir
  file:
    path="{{ es_data_dir }}"
    state=directory
    mode=0755
    recurse=true


- name: Create ElasticSerach Config Dir
  file:
    path="{{ es_config_dir }}"
    state=directory
    mode=0755
    recurse=true


- name: Create ElasticSerach Log Dir
  file:
    path="{{ es_log_dir }}"
    state=directory
    mode=0755
    recurse=true



- name: Create ElasticSerach Config File
  template:
    src=templates/elasticsearch.yml
    dest="{{ es_config_dir }}/elasticsearch.yml"
    owner=root
    group=docker
    mode=0644

#     {% for host in groups['app_servers'] %}
#       {{ hostvars[host]['ansible_eth0']['ipv4']['address'] }}
#     {% endfor %}



#    - name: Add Docker Keys
#      apt_key:
#        state=present
#        keyserver="hkp://p80.pool.sks-keyservers.net:80"
#        id="58118E89F3A912897C070ADBF76221572C52609D"
#
#
#    - name: Add Nodesource Apt Sources List Deb
#      apt_repository:
#        repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'
#        state=present
#      when: distrosupported|success
#
#
#
#    - name: Update apt cache
#      apt: update_cache=yes
#      sudo: yes
#
#
#
#
#
#
#    - name: Inastall Docker
#      apt: name={{ item }}
#      with_items:
#        -  docker-engine
#
#
#    - name: "Key123"
#      apt-key:
#        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
#        id: "58118E89F3A912897C070ADBF76221572C52609D"
#        state: present
#      register: add_repository_key
#      sudo: yes
#




