- name: Create ElasticSerach Config File
  template:
    src=templates/elasticsearch.yml
    dest="{{ es_config_dir }}/elasticsearch.yml"
    owner=root
    group=docker
    mode=0644


- name: Create ElasticSerach Config Log File
  template:
    src=templates/logging.yml
    dest="{{ es_config_dir }}/logging.yml"
    owner=root
    group=docker
    mode=0644

