- name: ElasticSearch Container
  docker:
    name: elasticsearch
    image: library/elasticsearch
    state: started
    pull: missing
    ports:
    - "{{ ansible_default_ipv4['address'] }}:9200:9200"
    - "{{ ansible_default_ipv4['address'] }}:9300:9300"

    extra_hosts:
      es-node-1: "{{ hostvars['node-1']['ansible_default_ipv4']['address'] }}"
      es-node-2: "{{ hostvars['node-2']['ansible_default_ipv4']['address'] }}"
      es-node-3: "{{ hostvars['node-3']['ansible_default_ipv4']['address'] }}"
    volumes:
    - "{{ es_data_dir }}:/usr/share/elasticsearch/data"
    - "{{ es_config_dir }}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    - "{{ es_log_dir }}:/usr/share/elasticsearch/log"
