network.host:  0.0.0.0
# {{ ansible_default_ipv4["address"] }}
cluster.name: production
node.name: ${HOSTNAME}
discovery.zen.ping.unicast.hosts: ["{{  hostvars["node-1"]["ansible_default_ipv4"]["address"] }}", "{{  hostvars["node-2"]["ansible_default_ipv4"]["address"] }}", "{{  hostvars["node-3"]["ansible_default_ipv4"]["address"] }}"]
discovery.zen.minimum_master_nodes: 2
