---
# tasks file for keepalived
- name: Include common vars
  include_vars: roles/common/defaults/main.yml

- name: Ensure notify script is executable
  file: path={{ keepalived_notify_script }} mode=0744

- name: Install keepalived
  apt: name=keepalived state=present # requires internet for now
  tags: keepalived

- name: Configure keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=running
  tags: keepalived