---
# Load available images in folder files/custom

  - name: Get list of images
    shell: "ls {{ docker_custom_tars_path }} | cut -d '.' -f 1"
    register: docker_images
    always_run: true

  - name: Ensure registry image removed before running new
    docker_image:
      name: '{{ item }}'
      state: absent
    with_items: '{{ docker_images.stdout_lines }}'

  - name: Load image from archive
    docker_image:
      name: '{{ item }}'
      load_path: '{{ docker_custom_tars_path }}/{{ item }}.tar'
    with_items: '{{ docker_images.stdout_lines }}'

  - name: Tag image for private registry
    shell: 'docker tag {{ item }} {{ docker_registry_ip }}:5000/{{ item }}:latest'
    with_items: '{{ docker_images.stdout_lines }}'

  - name: Push images to private registry # for using push from docker_image - ansible 2.2 required
    shell: 'docker push {{ docker_registry_ip }}:5000/{{ item }}:latest'
    with_items: '{{ docker_images.stdout_lines }}'