---
# tasks file for docker_registry

- name: "Deploy docker registry"
  include: registry.yml
  when: registry_role == "server"

- name: "Load custom images"
  include: images.yml
  when: registry_role == "server"

- name: "Deploy docker registry certificates"
  include: client.yml
  when: registry_role == "client"
  delegate_to: '{{ docker_registry_ip }}'

