---
- hosts: all
  roles:
      - common

- hosts: pr1
  roles:
     - { role: keepalived, keepalived_state: "master" }

- hosts: pr2
  roles:
     - { role: keepalived, keepalived_state: "backup" }

- hosts: pr1
  roles:
      - { role: docker_registry, registry_role: "server"}

- hosts: all
  roles:
      - { role: docker_registry, registry_role: "client"}

