---
- hosts: test
  roles:
      - common

- hosts: 192.168.122.3
  roles:
     - { role: keepalived, keepalived_state: "master" }

- hosts: 192.168.122.4
  roles:
     - { role: keepalived, keepalived_state: "backup" }


- hosts: 192.168.122.3
  roles:
      - { role: docker_registry, registry_role: "server"}

- hosts: test
  roles:
      - { role: docker_registry, registry_role: "client"}